-- Add migration script here

-- Function to rotate an API key (secret or publishable)
-- Note: Key material (hash, prefix, plaintext) must be generated by the application
-- layer for security reasons. This function only handles the atomic database operations.
CREATE OR REPLACE FUNCTION rotate_api_key(
    p_app_id UUID,
    p_user_id UUID,
    p_key_type key_type,
    p_new_key_hash TEXT DEFAULT NULL,
    p_new_key_prefix TEXT DEFAULT NULL,
    p_new_publishable_key_plaintext TEXT DEFAULT NULL,
    p_old_publishable_key TEXT DEFAULT NULL,
    p_description TEXT DEFAULT NULL
)
RETURNS TABLE (
    old_key_id UUID,
    new_key_id UUID,
    key_type key_type,
    scopes TEXT,
    old_key_hash TEXT,
    old_publishable_key_plaintext TEXT,
    created_at TIMESTAMPTZ
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_old_key RECORD;
    v_new_key_id UUID;
    v_new_created_at TIMESTAMPTZ;
    v_app applications%ROWTYPE;
BEGIN
    -- Validate application exists, belongs to user, and is active
    SELECT *
    INTO v_app
    FROM applications
    WHERE id = p_app_id
      AND developer_id = p_user_id
      AND is_active = TRUE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Application not found or inactive';
    END IF;

    -- Validate key material is provided based on key type
    IF p_key_type = 'secret' AND (p_new_key_hash IS NULL OR p_new_key_prefix IS NULL) THEN
        RAISE EXCEPTION 'Secret key rotation requires both key_hash and key_prefix';
    END IF;

    IF p_key_type = 'publishable' AND (p_new_publishable_key_plaintext IS NULL OR p_new_key_prefix IS NULL) THEN
        RAISE EXCEPTION 'Publishable key rotation requires both publishable_key_plaintext and key_prefix';
    END IF;

    -- Locate old key to deactivate
    IF p_key_type = 'secret' THEN
        SELECT *
        INTO v_old_key
        FROM api_keys
        WHERE application_id = p_app_id
          AND key_type = 'secret'
          AND is_active = TRUE
        LIMIT 1;

    ELSIF p_key_type = 'publishable' THEN
        IF p_old_publishable_key IS NOT NULL THEN
            -- Rotate specific publishable key
            SELECT *
            INTO v_old_key
            FROM api_keys
            WHERE publishable_key_plaintext = p_old_publishable_key
              AND application_id = p_app_id
              AND key_type = 'publishable'
              AND is_active = TRUE;
        ELSE
            -- Rotate oldest publishable key
            SELECT *
            INTO v_old_key
            FROM api_keys
            WHERE application_id = p_app_id
              AND key_type = 'publishable'
              AND is_active = TRUE
            ORDER BY created_at ASC
            LIMIT 1;
        END IF;
    ELSE
        RAISE EXCEPTION 'Invalid key type: must be secret or publishable';
    END IF;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Active % key not found for application', p_key_type;
    END IF;

    -- Deactivate old key
    UPDATE api_keys
    SET is_active = FALSE,
        updated_at = NOW()
    WHERE id = v_old_key.id;

    -- Create new key with provided key material
    INSERT INTO api_keys (
        id,
        application_id,
        user_id,
        key_type,
        key_hash,
        key_prefix,
        publishable_key_plaintext,
        description,
        scopes,
        is_active,
        created_at,
        updated_at
    )
    VALUES (
        gen_random_uuid(),
        p_app_id,
        p_user_id,
        p_key_type,
        p_new_key_hash,
        p_new_key_prefix,
        p_new_publishable_key_plaintext,
        COALESCE(p_description, v_old_key.description),
        v_old_key.scopes,
        TRUE,
        NOW(),
        NOW()
    )
    RETURNING id, created_at INTO v_new_key_id, v_new_created_at;

    -- Return rotation result
    RETURN QUERY
    SELECT
        v_old_key.id::UUID,
        v_new_key_id::UUID,
        p_key_type::key_type,
        v_old_key.scopes::TEXT,
        v_old_key.key_hash::TEXT,
        v_old_key.publishable_key_plaintext::TEXT,
        v_new_created_at::TIMESTAMPTZ;
END;
$$;

-- Grant execute permission to vaultless
GRANT EXECUTE ON FUNCTION rotate_api_key(UUID, UUID, key_type, TEXT, TEXT, TEXT, TEXT, TEXT) TO vaultless;
