-- Migration: Add create_application PostgreSQL function
-- Note: Key material (hash, prefix, plaintext) is generated by the application layer
-- for security and consistency. This function only handles database operations.

-- Function to create a new application with secret and publishable keys
CREATE OR REPLACE FUNCTION create_application(
    p_user_id UUID,
    p_name TEXT,
    p_description TEXT DEFAULT NULL,
    p_max_ttl_seconds INTEGER DEFAULT 604800,
    p_is_key_rotation_forced BOOLEAN DEFAULT FALSE,
    p_secret_key_hash TEXT DEFAULT NULL,
    p_secret_key_prefix TEXT DEFAULT NULL,
    p_publishable_key_plaintext TEXT DEFAULT NULL,
    p_publishable_key_prefix TEXT DEFAULT NULL
)
RETURNS TABLE (
    application_id UUID,
    user_id UUID,
    subscription_id UUID,
    name TEXT,
    description TEXT,
    is_active BOOLEAN,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    max_ttl_seconds BIGINT,
    is_key_rotation_forced BOOLEAN,
    deletion_requested_at TIMESTAMPTZ,
    internal_notes TEXT,
    app_meta JSONB,
    secret_key_prefix TEXT,
    publishable_key_plaintext TEXT
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_app_id UUID;
    v_app_row applications%ROWTYPE;
BEGIN
    -- Validate inputs
    IF LENGTH(TRIM(p_name)) = 0 THEN
        RAISE EXCEPTION 'Application name cannot be empty';
    END IF;

    IF p_max_ttl_seconds IS NOT NULL AND p_max_ttl_seconds <= 0 THEN
        RAISE EXCEPTION 'Max TTL seconds must be positive';
    END IF;

    -- Validate key material is provided
    IF p_secret_key_hash IS NULL OR p_secret_key_prefix IS NULL THEN
        RAISE EXCEPTION 'Secret key hash and prefix are required';
    END IF;

    IF p_publishable_key_plaintext IS NULL OR p_publishable_key_prefix IS NULL THEN
        RAISE EXCEPTION 'Publishable key plaintext and prefix are required';
    END IF;

    -- Generate application ID
    v_app_id := gen_random_uuid();

    -- Create the application
    INSERT INTO applications (
        id,
        developer_id,
        name,
        description,
        max_ttl_seconds,
        is_key_rotation_forced
    )
    VALUES (
        v_app_id,
        p_user_id,
        p_name,
        p_description,
        COALESCE(p_max_ttl_seconds, 604800),
        COALESCE(p_is_key_rotation_forced, FALSE)
    )
    RETURNING * INTO v_app_row;

    -- Create secret key with provided hash
    INSERT INTO api_keys (
        id,
        user_id,
        key_hash,
        key_prefix,
        description,
        is_active,
        created_at,
        updated_at,
        application_id,
        key_type
    )
    VALUES (
        gen_random_uuid(),
        p_user_id,
        p_secret_key_hash,
        p_secret_key_prefix,
        'Secret key for ' || p_name,
        TRUE,
        NOW(),
        NOW(),
        v_app_id,
        'secret'::key_type
    );

    -- Create publishable key with provided plaintext
    INSERT INTO api_keys (
        id,
        user_id,
        key_prefix,
        description,
        is_active,
        created_at,
        updated_at,
        application_id,
        key_type,
        publishable_key_plaintext
    )
    VALUES (
        gen_random_uuid(),
        p_user_id,
        p_publishable_key_prefix,
        'Publishable key for ' || p_name,
        TRUE,
        NOW(),
        NOW(),
        v_app_id,
        'publishable'::key_type,
        p_publishable_key_plaintext
    );

    -- Return the application and key information with proper type casting
    RETURN QUERY
    SELECT
        v_app_row.id,
        v_app_row.developer_id,
        v_app_row.subscription_id,
        v_app_row.name::TEXT,
        v_app_row.description::TEXT,
        v_app_row.is_active,
        v_app_row.created_at,
        v_app_row.updated_at,
        v_app_row.max_ttl_seconds::BIGINT,
        v_app_row.is_key_rotation_forced,
        v_app_row.deletion_requested_at,
        v_app_row.internal_notes::TEXT,
        v_app_row.app_meta,
        p_secret_key_prefix::TEXT,
        p_publishable_key_plaintext::TEXT;
END;
$$;

-- Grant execute permission
GRANT EXECUTE ON FUNCTION create_application(UUID, TEXT, TEXT, INTEGER, BOOLEAN, TEXT, TEXT, TEXT, TEXT) TO vaultless;